name: dhanrashi_mvp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.11.0
  flutter_svg: ^0.22.0
  flutter_rounded_date_picker: ^2.0.2
  matrix2d: ^1.0.0
  stacked: ^2.2.5
  intl: ^0.17.0
  tab_indicator_styler: ^2.0.0-null-safety
  font_awesome_flutter: ^9.1.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  cloud_firestore: ^1.0.0 #^2.5.1 # new
  firebase_auth: ^1.0.0 #^3.1.0
  #firebase_core: ^1.5.0 # new
  google_fonts: ^2.0.0
  fluttertoast: ^8.0.8
  loading_gifs: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/d-chart.png
    - images/legend.png
    - images/bubu1.jpg
    - images/bar_chart.png
    - images/dchart.png
    - images/legend1.png
    - images/famicar.png
    - images/house.jpg
    - images/SVG/logo_coloured.svg
    - images/SVG/logo_outline.svg
    - images/logo_coloured.png
    - images/confirmed.png
    - images/info.png
    - images/investing-pana.png
    - images/mutual.png
    - images/insurance.png
    - images/investment.png
    - images/investment_banner.png
    - images/profile_image.png
    - images/profile_image0.png
    - images/bank.png
    - images/bonds.png
    - images/real-estate.png
    - images/stock.png
    - images/coin.png
    - images/products.png
    - images/goals.png
    - images/car.png
    - images/destination.png
    - images/education.png
    - images/house.png
    - images/pension.png
    - images/tour.png
    - images/healthcare.png
    - images/goldsrain.png
    - images/empty.png
    - images/settings.png
    - images/no_connection.png
    - images/profiles/profile1.png
    - images/profiles/profile2.png
    - images/profiles/profile3.png
    - images/profiles/profile4.png
    - images/profiles/profile5.png
    - images/profiles/profile6.png
    - images/profiles/profile7.png
    - images/profiles/profile8.png
    - images/profiles/profile_image1.png
    - images/profiles/profile_image2.png
    - images/profiles/profile_image3.png
    - images/profiles/profile_image4.png
    - images/profiles/profile_image5.png
    - images/profiles/profile_image0.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/cabin-regular.ttf
        - asset: fonts/cabin-italics.ttf
    - family: Fredoka
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-ExtraBold.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
